ctfd:
  replicaCount: 1
  image:
    repository: ghcr.io/ctfd/ctfd
    pullPolicy: IfNotPresent
    tag: latest  
  env:
    open:
      # Required if more than 1 worker (randomly generate)
      SECRET_KEY: "ChangeMe!123"
      # Amount of CTFd workers
      WORKERS: 1
      # If behing ingress proxy or nginx:
      REVERSE_PROXY: True
  secret:
  existingSecret:
  # Stores Environment Variable to secret key name mappings
  existingSecretMappings:
    DATABASE_URL:
    REDIS_URL:

  config:
    enabled: false
    settings: |
      [server]
      SECRET_KEY =
      [extra]
      # Set needed config here

  probes:
    liveness:
      initialDelaySeconds: 25
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 5
    readiness:
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 5

  # For uploads to the CTFd server (images and other content)
  # Not for DB
  persistence:
    uploads:
      enabled: true
      #ReadWriteMany may be desired here if using multiple CTFd pods      
      accessMode: ReadWriteOnce
      size: 10Gi
      # existingClaim: 
      labels: {}
      # name: value
      # storageClass: "-"

nginx:
  replicaCount: 1
  image:
    repository: quay.io/cloud-architecture-workshop/globex-store-db
    pullPolicy: IfNotPresent
    tag: latest

redis:
  image:
    repository: registry.redhat.io/rhel9/redis-7
    pullPolicy: IfNotPresent
    tag: 9.5
  nameOverride: redis
  memory_limit: 512Mi
  redis_password: testp # TODO: must define a default value for .redis_password'
  pvc:
    volume_capacity: 1Gi
    app_code: "something"
    netapp_nfs: false

mariadb:
  image:
    repository: registry.redhat.io/rhel9/mariadb-1011 
    pullPolicy: IfNotPresent
    tag: 9.5
  nameOverride: mariadb
  memory_limit: 512Mi
  mysql_database: testdb
  mysql_password: testu
  mysql_root_password: testur
  mysql_user: testu
  namespace: openshift
  pvc:
    volume_capacity: 1Gi
    app_code: "something"
    netapp_nfs: false
