apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.name" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.openshift.io/runtime: redis
stringData:
  database-password: {{ .Values.redis.redis_password }}
type: Opaque