apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.openshift.io/runtime: redis
spec:
  ports:
  - name: redis
    nodePort: 0
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
