apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctfd.name" . }}-import
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
data:
  ctf_backup.zip: |-
    {{ .Files.Get "files/ctf_backup.zip" | b64enc | indent 4 }}