kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ctfd.name" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ctfd.pvc.volume_capacity | quote }}