apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.name" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}  
data:
  DATABASE_URL: {{ include "ctfd.DATABASE_URL" . | b64enc }}
  REDIS_URL: {{ include "ctfd.REDIS_URL" . | b64enc }}
type: Opaque  