apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ctfd.name" . }}-user-creation
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300  # Clean up job 5 minutes after completion
  backoffLimit: 3  # Retry up to 3 times on failure
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: user-creator
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Starting user creation job..."
              for i in $(seq 1 "$NUM_USERS"); do
                USERNAME="user-$i"
                EMAIL="$USERNAME@example.com"
                PASSWORD="password123"
                # Fetch nonce
                NONCE=$(curl -s -H "Authorization: Token $CTFD_API_KEY" http://{{ include "ctfd.name" . }}:8000/api/v1/users | grep -o '"nonce":"[^"]*"' | cut -d'"' -f4)
                if [ -z "$NONCE" ]; then
                  echo "Failed to retrieve nonce for $USERNAME" >&2
                  exit 1
                fi
                # Create user
                RESPONSE=$(curl -s -X POST \
                  -H "Authorization: Token $CTFD_API_KEY" \
                  -H "Content-Type: application/json" \
                  -d "{\"name\":\"$USERNAME\",\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\",\"nonce\":\"$NONCE\"}" \
                  http://{{ include "ctfd.name" . }}:8000/api/v1/users)
                if echo "$RESPONSE" | grep -q '"success": true'; then
                  echo "Successfully created $USERNAME"
                else
                  echo "Failed to create $USERNAME: $RESPONSE" >&2
                  exit 1
                fi
              done
              echo "All users created successfully"
          env:
            - name: NUM_USERS
              value: {{ .Values.ctfd.numUsers | default "5" | quote }}
            - name: CTFD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.name" . }}
                  key: "CTFD_API_KEY"