{{- if and .Values.ctfd.userCreation.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ctfd.name" . }}-user-creation
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"    
spec:
  backoffLimit: 3  # Retry up to 3 times on failure
  template:
    spec:
      restartPolicy: OnFailure 
      containers:
        - name: user-creator
          image: "{{ .Values.ctfd.userCreation.image.repository }}:{{ .Values.ctfd.userCreation.image.tag }}"          
          command:
            - sh
            - -c
            - |
              echo "Starting user creation job..."
              for i in $(seq 1 "$USER_COUNT"); do
                USERNAME="$USER_PREFIX$i"
                EMAIL="$USERNAME@example.com"
                PASSWORD="$USER_DEFAULT_PASSWORD"
                # Create user
                RESPONSE=$(curl -s -X POST \
                  -H "Authorization: Token $CTFD_API_KEY" \
                  -H "Content-Type: application/json" \
                  -d "{\"name\":\"$USERNAME\",\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\",\"type\":\"user\"}" \
                  https://$CTFD_ROUTE/api/v1/users)
                if echo "$RESPONSE" | grep -q '"success": true'; then
                  echo "Successfully created $USERNAME"
                else
                  echo "Failed to create $USERNAME: $RESPONSE" >&2
                  exit 1
                fi
              done
              echo "All users created successfully"
          env:
            - name: USER_COUNT
              value: {{ .Values.ctfd.userCreation.userCount | quote}}
            - name: USER_PREFIX
              value: {{ .Values.ctfd.userCreation.userPrefix }}                
            - name: USER_DEFAULT_PASSWORD
              value: {{ .Values.ctfd.userCreation.userDefaultPassword }}              
            - name: CTFD_ROUTE
              value: {{ include "ctfd.name" . }}-{{ .Values.namespace }}.{{ .Values.appsSubdomain }} 
            - name: CTFD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctfd.name" . }}
                  key: "CTFD_API_KEY"
{{- end }}                  