apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.openshift.io/runtime: mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.pvc.volume_capacity }}
