apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.openshift.io/runtime: mariadb
stringData:
  database-name: {{ .Values.mariadb.mysql_database }}
  database-password: {{ .Values.mariadb.mysql_password }}
  database-root-password: {{ .Values.mariadb.mysql_root_password }}
  database-user: {{ .Values.mariadb.mysql_user }}
type: Opaque