apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.openshift.io/runtime: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}