apiVersion: v2
name: ctfd
description: A Helm chart for CTFd
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: mariadb
    repository: file://../mariadb
    condition: mariadb.enabled
  - name: redis
    repository: file://../redis
    condition: redis.enabled