ctfd:
  replicaCount: 1
  image:
    repository: ghcr.io/ctfd/ctfd
    pullPolicy: IfNotPresent
    tag: latest
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi    
  env:
    - name: WORKERS
      value: "2"
    - name: ACCESS_LOG
      value: "-"
    - name: ERROR_LOG
      value: "-"
    - name: REVERSE_PROXY
      value: "true"
    - name: LOG_FOLDER
      value: "/var/log/CTFd"
    - name: UPLOAD_PROVIDER
      value: "s3"  # The chart only supports S3
  persistence:
    uploads:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
  port: 8000    

nginx:
  replicaCount: 1
  image:
    repository: quay.io/cloud-architecture-workshop/globex-store-db
    pullPolicy: IfNotPresent
    tag: latest